language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install pylint coverage
  - pip install -e .
script:
  - nosetests -s -q --with-coverage --cover-package=enocean
env:
  - WITH_TIMINGS=0
  - WITH_TIMINGS=1
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - env: WITH_TIMINGS=1

after_success:
  - pylint enocean -d line-too-long
